// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ynvFHQxELeKkNTL-M5qIbTDdOiZGQqA',
    appId: '1:1008667053039:web:8228f4e01d54ca7f14c41a',
    messagingSenderId: '1008667053039',
    projectId: 'e-saver-d89e8',
    authDomain: 'e-saver-d89e8.firebaseapp.com',
    storageBucket: 'e-saver-d89e8.firebasestorage.app',
    measurementId: 'G-4X30JH4G7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Z-SB53YYlaZoQg7k3s4PXZkKwuufZrc',
    appId: '1:1008667053039:android:27ff31aebbd312dd14c41a',
    messagingSenderId: '1008667053039',
    projectId: 'e-saver-d89e8',
    storageBucket: 'e-saver-d89e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiJZAn8zpR27EZwU1eOADSEpCykayZZOI',
    appId: '1:1008667053039:ios:a7be062b91ced32b14c41a',
    messagingSenderId: '1008667053039',
    projectId: 'e-saver-d89e8',
    storageBucket: 'e-saver-d89e8.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiJZAn8zpR27EZwU1eOADSEpCykayZZOI',
    appId: '1:1008667053039:ios:a7be062b91ced32b14c41a',
    messagingSenderId: '1008667053039',
    projectId: 'e-saver-d89e8',
    storageBucket: 'e-saver-d89e8.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ynvFHQxELeKkNTL-M5qIbTDdOiZGQqA',
    appId: '1:1008667053039:web:16ceb509ec5c3d4d14c41a',
    messagingSenderId: '1008667053039',
    projectId: 'e-saver-d89e8',
    authDomain: 'e-saver-d89e8.firebaseapp.com',
    storageBucket: 'e-saver-d89e8.firebasestorage.app',
    measurementId: 'G-LHR02TKQZD',
  );
}
